### ISSUE TITLE
No longer works with mbed OS 5.5

### ISSUE THREAD

**Issue by janjongboom** [nuket/mbed-memory-status#7]
mbed OS 5.5 updated RTX to RTX5, and the APIs have changed a bit for retrieving threads and stack sizes.

This is what I'm currently using:

```
    mbed_stats_heap_t heap_stats;
    mbed_stats_heap_get(&heap_stats);
    printf("Heap size: %lu / %lu\r\n", heap_stats.current_size, heap_stats.reserved_size);

    osThreadId_t threads[20];

    uint32_t thread_count = osThreadEnumerate(threads, 20);

    for (size_t ix = 0; ix < thread_count; ix++) {
      osThreadId_t threadId = threads[ix];

      printf("[%s] Stack size: %lu / %lu\n", osThreadGetName(threadId), osThreadGetStackSize(threadId), osThreadGetStackSpace(threadId));
    }
```

**Comment by nuket** [comment]
Nice. I'll take a look at adding something like this. Now if only there were some movement on https://github.com/ARMmbed/mbed-os/issues/4891 so I don't have to convert my code to `extern "C"` wrapped C++. 😄

**Comment by janjongboom** [comment]
@nuket, Ah! Didn't spot that. However, if you want the lib to be compatible with both old and new versions of RTX you'll need access to those macros, so that'd require wrapping the code anyway, regardless of whether 4891 gets fixed.

**Comment by nuket** [comment]
Finally found a moment to fix this properly using the `osCMSIS` macro from `cmsis_os.h`.

This somewhat eliminates the need for a fix to https://github.com/ARMmbed/mbed-os/issues/4891, at least for this use case.
